/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inscription d'un nouvel utilisateur (Freelance ou Recruteur) */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentification : access token dans le body, refresh token en cookie httpOnly */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotation du refresh token (lu depuis le cookie, ou le body pour le mobile) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Déconnexion : révocation du refresh token (Redis) et expiration du cookie */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État 2FA du compte courant (le JWT ne porte pas cette information) */
        get: operations["TwoFactorController_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Démarrer l'enrôlement 2FA (génère le secret TOTP, chiffré en base) */
        post: operations["TwoFactorController_enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmer l'enrôlement avec le premier code : ACTIVE la 2FA */
        post: operations["TwoFactorController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Étape 2 du login : jeton d'étape + code TOTP (ou code de secours) => vrais tokens */
        post: operations["TwoFactorController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Désactiver la 2FA (exige un code valide) : purge secret + codes de secours */
        post: operations["TwoFactorController_disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/backup-codes/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Régénérer les codes de secours (les anciens sont invalidés) */
        post: operations["TwoFactorController_regenerateBackupCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Déclarer un équipement dans son casier (Freelance) */
        post: operations["GearController_addGear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gear/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister son propre matériel (filtres + pagination) */
        get: operations["GearController_getMyGear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gear/freelance/{freelanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulter le matériel VALIDÉ d'un freelance (Recruteur) */
        get: operations["GearController_getPublicFreelanceGear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gear/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File de validation : matériel en attente (Admin) */
        get: operations["GearController_getPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gear/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Valider ou rejeter un équipement (Admin) */
        patch: operations["GearController_review"];
        trace?: never;
    };
    "/api/v1/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Uploader une certification PDF (Freelance) */
        post: operations["CertificationController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certifications/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister ses propres certifications (métadonnées + statut) */
        get: operations["CertificationController_getMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certifications/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File de validation : certifications en attente (Admin) */
        get: operations["CertificationController_getPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certifications/{id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtenir une Signed URL du document (propriétaire ou Admin) */
        get: operations["CertificationController_getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certifications/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Valider ou rejeter une certification + purge RGPD (Admin) */
        patch: operations["CertificationController_review"];
        trace?: never;
    };
    "/api/v1/matching/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rechercher des freelances par matching multicritères (Recruteur) */
        post: operations["MatchingController_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LocationDto: {
            /**
             * @description Latitude en degrés décimaux (WGS84, entre -90 et 90)
             * @example 43.6045
             */
            latitude: number;
            /**
             * @description Longitude en degrés décimaux (WGS84, entre -180 et 180)
             * @example 1.4442
             */
            longitude: number;
        };
        RegisterDto: {
            /**
             * @description Email unique de l'utilisateur
             * @example pilote.expert@skillhunt.io
             */
            email: string;
            /**
             * @description Nom d'utilisateur unique
             * @example MarcusThorne
             */
            username: string;
            /**
             * @description Mot de passe fort (8 caractères minimum)
             * @example P@ssw0rdSecureDrone2026
             */
            password: string;
            /**
             * @description FREELANCE ou RECRUITER (le rôle ADMIN n'est pas auto-attribuable)
             * @example FREELANCE
             * @enum {string}
             */
            role: "FREELANCE" | "RECRUITER";
            /** @description Position géographique. OBLIGATOIRE pour un FREELANCE (sinon invisible du matching par rayon, SH-13) ; optionnelle pour un RECRUITER. */
            location?: components["schemas"]["LocationDto"];
        };
        LoginDto: {
            /** @example pilote.expert@skillhunt.io */
            email: string;
            /** @example P@ssw0rdSecureDrone2026 */
            password: string;
        };
        RefreshDto: {
            /** @description Refresh token (JWT). Inutile pour le web : le cookie httpOnly fait foi. */
            refreshToken?: string;
        };
        EnrollResponseDto: {
            /**
             * @description Secret TOTP (base32), à ne jamais re-consulter
             * @example JBSWY3DPEHPK3PXP
             */
            secret: string;
            /**
             * @description URI otpauth à encoder en QR code côté client
             * @example otpauth://totp/SkillHunt:pro%40skillhunt.io?secret=…
             */
            otpauthUrl: string;
        };
        TwoFactorCodeDto: {
            /**
             * @description Code TOTP (6 chiffres) ou code de secours
             * @example 123456
             */
            code: string;
        };
        BackupCodesResponseDto: {
            /**
             * @description Codes de secours à usage unique — stockés hachés, jamais re-consultables
             * @example [
             *       "A2C4-E6G8",
             *       "K3M5-P7R9"
             *     ]
             */
            backupCodes: string[];
        };
        VerifyTwoFactorDto: {
            /** @description Jeton d'étape 2FA émis par /login (validité 5 min) */
            twoFactorToken: string;
            /**
             * @description Code TOTP (6 chiffres) ou code de secours
             * @example 123456
             */
            code: string;
        };
        AddGearDto: {
            /**
             * @description Catégorie de matériel
             * @example DRONE
             * @enum {string}
             */
            category: "DRONE" | "CAMERA_360" | "ROBOTICS" | "SENSOR" | "OTHER";
            /**
             * @description Marque de l'équipement
             * @example DJI
             */
            brand: string;
            /**
             * @description Modèle exact
             * @example Mavic 3 Enterprise
             */
            model: string;
            /**
             * @description Numéro de série pour vérification anti-vol/assurance
             * @example SN-123456789
             */
            serialNumber: string;
        };
        GearResponseDto: {
            /**
             * Format: uuid
             * @example 3f1b2c9e-6d54-4a1b-9d0e-7c2f5a8b1234
             */
            id: string;
            /**
             * @description Marque de l'équipement
             * @example DJI
             */
            brand: string;
            /**
             * @description Modèle exact
             * @example Mavic 3 Enterprise
             */
            model: string;
            /**
             * @description Numéro de série — donnée sensible : renvoyée uniquement au propriétaire du casier, jamais dans une vue publique (SH-39)
             * @example SN-123456789
             */
            serialNumber: string;
            /**
             * @example DRONE
             * @enum {string}
             */
            category: "DRONE" | "CAMERA_360" | "ROBOTICS" | "SENSOR" | "OTHER";
            /**
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "VALIDATED" | "REJECTED";
            /**
             * Format: date-time
             * @example 2026-07-14T09:12:33.000Z
             */
            createdAt: string;
            /**
             * Format: uuid
             * @description Propriétaire (Freelance) — déduit du token, jamais d'un identifiant client
             */
            freelanceId: string;
        };
        PaginatedGearDto: {
            items: components["schemas"]["GearResponseDto"][];
            /**
             * @description Nombre total d'équipements correspondant au filtre appliqué
             * @example 12
             */
            total: number;
            /**
             * @description Page courante (1-indexée)
             * @example 1
             */
            page: number;
            /**
             * @description Taille de page appliquée
             * @example 20
             */
            limit: number;
        };
        PublicGearDto: {
            /**
             * Format: uuid
             * @example 3f1b2c9e-6d54-4a1b-9d0e-7c2f5a8b1234
             */
            id: string;
            /**
             * @description Marque de l'équipement
             * @example DJI
             */
            brand: string;
            /**
             * @description Modèle exact
             * @example Mavic 3 Enterprise
             */
            model: string;
            /**
             * @example DRONE
             * @enum {string}
             */
            category: "DRONE" | "CAMERA_360" | "ROBOTICS" | "SENSOR" | "OTHER";
            /**
             * @example PENDING
             * @enum {string}
             */
            status: "PENDING" | "VALIDATED" | "REJECTED";
            /**
             * Format: date-time
             * @example 2026-07-14T09:12:33.000Z
             */
            createdAt: string;
        };
        PaginatedPublicGearDto: {
            items: components["schemas"]["PublicGearDto"][];
            /**
             * @description Nombre total d'équipements validés du freelance
             * @example 12
             */
            total: number;
            /**
             * @description Page courante (1-indexée)
             * @example 1
             */
            page: number;
            /**
             * @description Taille de page appliquée
             * @example 20
             */
            limit: number;
        };
        ReviewGearDto: {
            /**
             * @description Décision de validation : VALIDATED ou REJECTED
             * @example VALIDATED
             * @enum {string}
             */
            decision: "VALIDATED" | "REJECTED";
        };
        ReviewCertificationDto: {
            /**
             * @description Décision de validation : VALIDATED ou REJECTED
             * @example VALIDATED
             * @enum {string}
             */
            decision: "VALIDATED" | "REJECTED";
            /**
             * Format: date-time
             * @description Date de validité confirmée/corrigée par l'Admin (optionnel)
             * @example 2027-12-31
             */
            validUntil?: string;
        };
        SearchMatchDto: {
            /**
             * @description Compétences recherchées (1 à 50, chacune de 1 à 64 caractères)
             * @example [
             *       "pilotage drone",
             *       "thermographie"
             *     ]
             */
            skills: string[];
            /**
             * @description Latitude du lieu de mission
             * @example 43.6045
             */
            lat: number;
            /**
             * @description Longitude du lieu de mission
             * @example 1.4442
             */
            lon: number;
            /**
             * @description Rayon d'action en kilomètres (0 < r ≤ 500)
             * @example 50
             */
            radiusKm: number;
        };
        MatchResultDto: {
            /**
             * Format: uuid
             * @example 3f1b2c9e-6d54-4a1b-9d0e-7c2f5a8b1234
             */
            freelanceId: string;
            /**
             * @description Username du freelance — null si le compte a disparu entre-temps
             * @example pilote-pro
             */
            username: string | null;
            /**
             * @description Score de matching (0..1)
             * @example 0.92
             */
            score: number;
            /**
             * @description Distance au lieu de mission (km)
             * @example 12.5
             */
            distanceKm: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Utilisateur créé avec succès (sans exposer le hash). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Jetons JWT RS256 émis ; cookie `sh_refresh` déposé. Si la 2FA est active (SH-40) : `{ twoFactorRequired: true, twoFactorToken }` — AUCUN token ni cookie avant /auth/2fa/verify. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description Nouveau couple émis ; l'ancien refresh token est révoqué. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token absent, invalide, expiré ou révoqué. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description Refresh token révoqué (opération idempotente). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TwoFactorController_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `{ enabled: boolean }` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TwoFactorController_enroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Secret + URI otpauth (affichés une seule fois) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResponseDto"];
                };
            };
            /** @description 2FA déjà activée sur ce compte */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TwoFactorController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFactorCodeDto"];
            };
        };
        responses: {
            /** @description Codes de secours — affichés UNE seule fois */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupCodesResponseDto"];
                };
            };
            /** @description Code invalide : la 2FA reste inactive */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TwoFactorController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyTwoFactorDto"];
            };
        };
        responses: {
            /** @description Connexion complétée : tokens émis, cookie sh_refresh déposé */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Jeton d'étape expiré ou code invalide */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trop de tentatives : compte temporairement verrouillé */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TwoFactorController_disable: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFactorCodeDto"];
            };
        };
        responses: {
            /** @description Code invalide : la 2FA reste active */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TwoFactorController_regenerateBackupCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TwoFactorCodeDto"];
            };
        };
        responses: {
            /** @description Nouveaux codes — affichés UNE seule fois */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupCodesResponseDto"];
                };
            };
        };
    };
    GearController_addGear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddGearDto"];
            };
        };
        responses: {
            /** @description Équipement déclaré, en attente de validation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GearResponseDto"];
                };
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant pour cette ressource (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GearController_getMyGear: {
        parameters: {
            query?: {
                /** @description Filtrer par catégorie */
                category?: "DRONE" | "CAMERA_360" | "ROBOTICS" | "SENSOR" | "OTHER";
                /** @description Filtrer par statut de validation */
                status?: "PENDING" | "VALIDATED" | "REJECTED";
                /** @description Numéro de page (1-indexé) */
                page?: number;
                /** @description Taille de page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page du casier du Freelance authentifié */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGearDto"];
                };
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant pour cette ressource (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GearController_getPublicFreelanceGear: {
        parameters: {
            query?: {
                /** @description Filtrer par catégorie */
                category?: "DRONE" | "CAMERA_360" | "ROBOTICS" | "SENSOR" | "OTHER";
                /** @description Numéro de page (1-indexé) */
                page?: number;
                /** @description Taille de page */
                limit?: number;
            };
            header?: never;
            path: {
                freelanceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matériel validé uniquement, sans donnée sensible (jamais de serialNumber) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPublicGearDto"];
                };
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant pour cette ressource (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Profil Freelance introuvable (404) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GearController_getPending: {
        parameters: {
            query?: {
                /** @description Filtrer par catégorie */
                category?: "DRONE" | "CAMERA_360" | "ROBOTICS" | "SENSOR" | "OTHER";
                /** @description Filtrer par statut de validation */
                status?: "PENDING" | "VALIDATED" | "REJECTED";
                /** @description Numéro de page (1-indexé) */
                page?: number;
                /** @description Taille de page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page des équipements en attente de validation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGearDto"];
                };
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant pour cette ressource (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GearController_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewGearDto"];
            };
        };
        responses: {
            /** @description Équipement après décision (VALIDATED ou REJECTED) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GearResponseDto"];
                };
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant pour cette ressource (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CertificationController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Document PDF (≤ 5 Mo)
                     */
                    file: string;
                    /** @enum {string} */
                    type: "DGAC_DRONE" | "ELEC_HABILITATION" | "OTHER";
                    /** @example FR-DGAC-2024-123456 */
                    number: string;
                    /**
                     * Format: date
                     * @example 2027-12-31
                     */
                    validUntil: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant ou accès à une ressource d'autrui (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CertificationController_getMine: {
        parameters: {
            query?: {
                /** @description Filtrer par statut de validation */
                status?: "PENDING" | "VALIDATED" | "REJECTED";
                /** @description Numéro de page (1-indexé) */
                page?: number;
                /** @description Taille de page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant ou accès à une ressource d'autrui (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CertificationController_getPending: {
        parameters: {
            query?: {
                /** @description Filtrer par statut de validation */
                status?: "PENDING" | "VALIDATED" | "REJECTED";
                /** @description Numéro de page (1-indexé) */
                page?: number;
                /** @description Taille de page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant ou accès à une ressource d'autrui (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CertificationController_getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant ou accès à une ressource d'autrui (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CertificationController_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCertificationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant ou accès à une ressource d'autrui (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MatchingController_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchMatchDto"];
            };
        };
        responses: {
            /** @description Résultats triés (score décroissant, distance croissante), enrichis du username */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResultDto"][];
                };
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant pour cette ressource (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Matching-service indisponible (502) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
