/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inscription d'un nouvel utilisateur (Freelance ou Recruteur) */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authentification : access token dans le body, refresh token en cookie httpOnly */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotation du refresh token (lu depuis le cookie, ou le body pour le mobile) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Déconnexion : révocation du refresh token (Redis) et expiration du cookie */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Déclarer un équipement dans son casier (Freelance) */
        post: operations["GearController_addGear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gear/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister son propre matériel (filtres + pagination) */
        get: operations["GearController_getMyGear"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gear/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File de validation : matériel en attente (Admin) */
        get: operations["GearController_getPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gear/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Valider ou rejeter un équipement (Admin) */
        patch: operations["GearController_review"];
        trace?: never;
    };
    "/api/v1/certifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Uploader une certification PDF (Freelance) */
        post: operations["CertificationController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certifications/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lister ses propres certifications (métadonnées + statut) */
        get: operations["CertificationController_getMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certifications/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File de validation : certifications en attente (Admin) */
        get: operations["CertificationController_getPending"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certifications/{id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtenir une Signed URL du document (propriétaire ou Admin) */
        get: operations["CertificationController_getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certifications/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Valider ou rejeter une certification + purge RGPD (Admin) */
        patch: operations["CertificationController_review"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description Email unique de l'utilisateur
             * @example pilote.expert@skillhunt.io
             */
            email: string;
            /**
             * @description Nom d'utilisateur unique
             * @example MarcusThorne
             */
            username: string;
            /**
             * @description Mot de passe fort (8 caractères minimum)
             * @example P@ssw0rdSecureDrone2026
             */
            password: string;
            /**
             * @description FREELANCE ou RECRUITER (le rôle ADMIN n'est pas auto-attribuable)
             * @example FREELANCE
             * @enum {string}
             */
            role: "FREELANCE" | "RECRUITER";
        };
        LoginDto: {
            /** @example pilote.expert@skillhunt.io */
            email: string;
            /** @example P@ssw0rdSecureDrone2026 */
            password: string;
        };
        RefreshDto: {
            /** @description Refresh token (JWT). Inutile pour le web : le cookie httpOnly fait foi. */
            refreshToken?: string;
        };
        AddGearDto: {
            /**
             * @description Catégorie de matériel
             * @example DRONE
             * @enum {string}
             */
            category: "DRONE" | "CAMERA_360" | "ROBOTICS" | "SENSOR" | "OTHER";
            /**
             * @description Marque de l'équipement
             * @example DJI
             */
            brand: string;
            /**
             * @description Modèle exact
             * @example Mavic 3 Enterprise
             */
            model: string;
            /**
             * @description Numéro de série pour vérification anti-vol/assurance
             * @example SN-123456789
             */
            serialNumber: string;
        };
        ReviewGearDto: {
            /**
             * @description Décision de validation : VALIDATED ou REJECTED
             * @example VALIDATED
             * @enum {string}
             */
            decision: "VALIDATED" | "REJECTED";
        };
        ReviewCertificationDto: {
            /**
             * @description Décision de validation : VALIDATED ou REJECTED
             * @example VALIDATED
             * @enum {string}
             */
            decision: "VALIDATED" | "REJECTED";
            /**
             * Format: date-time
             * @description Date de validité confirmée/corrigée par l'Admin (optionnel)
             * @example 2027-12-31
             */
            validUntil?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Utilisateur créé avec succès (sans exposer le hash). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Jetons JWT RS256 émis ; cookie `sh_refresh` déposé. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description Nouveau couple émis ; l'ancien refresh token est révoqué. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token absent, invalide, expiré ou révoqué. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description Refresh token révoqué (opération idempotente). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GearController_addGear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddGearDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant pour cette ressource (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GearController_getMyGear: {
        parameters: {
            query?: {
                /** @description Filtrer par catégorie */
                category?: "DRONE" | "CAMERA_360" | "ROBOTICS" | "SENSOR" | "OTHER";
                /** @description Filtrer par statut de validation */
                status?: "PENDING" | "VALIDATED" | "REJECTED";
                /** @description Numéro de page (1-indexé) */
                page?: number;
                /** @description Taille de page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant pour cette ressource (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GearController_getPending: {
        parameters: {
            query?: {
                /** @description Filtrer par catégorie */
                category?: "DRONE" | "CAMERA_360" | "ROBOTICS" | "SENSOR" | "OTHER";
                /** @description Filtrer par statut de validation */
                status?: "PENDING" | "VALIDATED" | "REJECTED";
                /** @description Numéro de page (1-indexé) */
                page?: number;
                /** @description Taille de page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant pour cette ressource (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GearController_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewGearDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant pour cette ressource (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CertificationController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Document PDF (≤ 5 Mo)
                     */
                    file: string;
                    /** @enum {string} */
                    type: "DGAC_DRONE" | "ELEC_HABILITATION" | "OTHER";
                    /** @example FR-DGAC-2024-123456 */
                    number: string;
                    /**
                     * Format: date
                     * @example 2027-12-31
                     */
                    validUntil: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant ou accès à une ressource d'autrui (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CertificationController_getMine: {
        parameters: {
            query?: {
                /** @description Filtrer par statut de validation */
                status?: "PENDING" | "VALIDATED" | "REJECTED";
                /** @description Numéro de page (1-indexé) */
                page?: number;
                /** @description Taille de page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant ou accès à une ressource d'autrui (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CertificationController_getPending: {
        parameters: {
            query?: {
                /** @description Filtrer par statut de validation */
                status?: "PENDING" | "VALIDATED" | "REJECTED";
                /** @description Numéro de page (1-indexé) */
                page?: number;
                /** @description Taille de page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant ou accès à une ressource d'autrui (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CertificationController_getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant ou accès à une ressource d'autrui (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CertificationController_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCertificationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token JWT manquant, invalide ou expiré (401) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rôle insuffisant ou accès à une ressource d'autrui (403) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
